/**
 * Demo connections for Referrals → My network, as in Figma's `My network` frame (Verita, `node-id=6156-5828`). Spec:
 * `product-specs/referrals.md` §5.2 (columns, filters) and §8 (activity events).
 *
 * The first seven are Figma's people, job titles, and match counts. The referral numbers are made consistent with each
 * other and with My referrals (design direction, 2026-10-03): a connection's `Referrals` and `Last activity` follow
 * their rows in `DEMO_REFERRALS`, `Earned` counts only rewards those referrals earned, and a connection with no current
 * matches has no potential.
 *
 * The other 36 (2026-10-03) fill the network out to 43, like an imported LinkedIn network: people across finance,
 * healthcare, data, AI, legal, and operations, none referred yet. About a third match current opportunities, a few of
 * them newly; the rest have no matches and no activity yet.
 */

/** `Last activity` and the activity filter's values (`referrals.md` §8). */
const CONNECTION_ACTIVITIES = [
  "Referral created",
  "Applied",
  "Started working",
  "Reward earned",
  "New match surfaced",
] as const;

type ConnectionActivity = (typeof CONNECTION_ACTIVITIES)[number];

interface DemoConnection {
  key: string;
  name: string;
  /** Current or most recent job title, under the name (§5.2: more useful than email for judging fit). */
  jobTitle: string;
  /** Fallback identifier: searchable, not shown in the table. */
  email: string;
  avatarSrc?: string;
  /** Initials avatar background, when there's no photo (the same colors as these people's My referrals rows). */
  avatarClassName?: string;
  /** Current active opportunities they match (`Matches`). */
  matches: number;
  /** A match surfaced recently (`New matches` filter). */
  newMatch?: boolean;
  /** The latest activity event (§8). Omitted for a connection with no referrals and no matches yet (shown as `—`). */
  lastActivity?: ConnectionActivity;
  /** Lifetime referral records for this connection (`Referrals`). */
  referrals: number;
  /** Lifetime rewards earned through their referrals, USD (`Earned`). */
  earned: number;
  /** What their current matches could earn, USD (`Potential`); the sum of the matched opportunities' rewards. */
  potential: number;
}

const photo = (file: string) => new URL(`../referrals/images/${file}`, import.meta.url).href;

const DEMO_CONNECTIONS: DemoConnection[] = [
  {
    key: "olivia-smith",
    name: "Olivia Smith",
    jobTitle: "Senior Financial Analyst",
    email: "olivia.smith@email.com",
    avatarSrc: photo("avatar-olivia-smith.png"),
    matches: 3,
    lastActivity: "Referral created",
    referrals: 2,
    earned: 0,
    potential: 1050,
  },
  {
    key: "kristin-watson",
    name: "Kristin Watson",
    jobTitle: "Senior Financial Analyst",
    email: "kristin.watson@email.com",
    avatarSrc: photo("avatar-kristin-watson.png"),
    matches: 1,
    newMatch: true,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 450,
  },
  {
    key: "courtney-henry",
    name: "Courtney Henry",
    jobTitle: "Machine Learning Engineer",
    email: "courtney.henry@email.com",
    avatarSrc: photo("avatar-courtney-henry.png"),
    matches: 0,
    lastActivity: "Applied",
    referrals: 1,
    earned: 0,
    potential: 0,
  },
  {
    key: "leslie-alexander",
    name: "Leslie Alexander",
    jobTitle: "Product Manager",
    email: "leslie.alexander@email.com",
    avatarClassName: "bg-tone-success",
    matches: 0,
    lastActivity: "Applied",
    referrals: 1,
    earned: 0,
    potential: 0,
  },
  {
    key: "albert-flores",
    name: "Albert Flores",
    jobTitle: "Software Engineer",
    email: "albert.flores@email.com",
    avatarClassName: "bg-tone-warning",
    matches: 1,
    lastActivity: "Started working",
    referrals: 1,
    earned: 0,
    potential: 300,
  },
  {
    key: "jacob-jones",
    name: "Jacob Jones",
    jobTitle: "Data Analyst",
    email: "jacob.jones@email.com",
    avatarSrc: photo("avatar-jacob-jones.png"),
    matches: 2,
    // A new match on someone already referred: `Referred` and `New matches` aren't exclusive (§5.2).
    newMatch: true,
    lastActivity: "Reward earned",
    referrals: 1,
    earned: 50,
    potential: 600,
  },
  {
    key: "bessie-cooper",
    name: "Bessie Cooper",
    jobTitle: "Operations Manager",
    email: "bessie.cooper@email.com",
    avatarClassName: "bg-tone-orange",
    matches: 0,
    lastActivity: "Reward earned",
    referrals: 1,
    earned: 50,
    potential: 0,
  },
  // The rest of the network: imported, not referred yet.
  {
    key: "marcus-chen",
    name: "Marcus Chen",
    jobTitle: "FP&A Manager",
    email: "marcus.chen@email.com",
    avatarClassName: "bg-tone-info",
    matches: 2,
    newMatch: true,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 750,
  },
  {
    key: "priya-raman",
    name: "Priya Raman",
    jobTitle: "Clinical Research Coordinator",
    email: "priya.raman@email.com",
    avatarClassName: "bg-tone-indigo",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "daniel-okafor",
    name: "Daniel Okafor",
    jobTitle: "Corporate Controller",
    email: "daniel.okafor@email.com",
    avatarClassName: "bg-tone-purple",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 450,
  },
  {
    key: "sofia-martinez",
    name: "Sofia Martinez",
    jobTitle: "Registered Nurse",
    email: "sofia.martinez@email.com",
    avatarClassName: "bg-tone-pink",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "ethan-brooks",
    name: "Ethan Brooks",
    jobTitle: "Machine Learning Engineer",
    email: "ethan.brooks@email.com",
    avatarClassName: "bg-tone-success",
    matches: 2,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 600,
  },
  {
    key: "hannah-lee",
    name: "Hannah Lee",
    jobTitle: "Data Scientist",
    email: "hannah.lee@email.com",
    avatarClassName: "bg-tone-warning",
    matches: 1,
    newMatch: true,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "omar-haddad",
    name: "Omar Haddad",
    jobTitle: "Senior Accountant",
    email: "omar.haddad@email.com",
    avatarClassName: "bg-tone-orange",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "grace-kim",
    name: "Grace Kim",
    jobTitle: "Healthcare Data Analyst",
    email: "grace.kim@email.com",
    avatarClassName: "bg-tone-info",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "lucas-ferreira",
    name: "Lucas Ferreira",
    jobTitle: "Investment Analyst",
    email: "lucas.ferreira@email.com",
    avatarClassName: "bg-tone-indigo",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 450,
  },
  {
    key: "amara-nwosu",
    name: "Amara Nwosu",
    jobTitle: "Paralegal",
    email: "amara.nwosu@email.com",
    avatarClassName: "bg-tone-purple",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "noah-patel",
    name: "Noah Patel",
    jobTitle: "Software Engineer",
    email: "noah.patel@email.com",
    avatarClassName: "bg-tone-pink",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "chloe-dubois",
    name: "Chloe Dubois",
    jobTitle: "UX Researcher",
    email: "chloe.dubois@email.com",
    avatarClassName: "bg-tone-success",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "ryan-oconnor",
    name: "Ryan O’Connor",
    jobTitle: "Insurance Underwriter",
    email: "ryan.oconnor@email.com",
    avatarClassName: "bg-tone-warning",
    matches: 1,
    newMatch: true,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "mei-tanaka",
    name: "Mei Tanaka",
    jobTitle: "Pharmacist",
    email: "mei.tanaka@email.com",
    avatarClassName: "bg-tone-orange",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "jonah-weiss",
    name: "Jonah Weiss",
    jobTitle: "Strategy Consultant",
    email: "jonah.weiss@email.com",
    avatarClassName: "bg-tone-info",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "isabel-rossi",
    name: "Isabel Rossi",
    jobTitle: "Financial Planning Analyst",
    email: "isabel.rossi@email.com",
    avatarClassName: "bg-tone-indigo",
    matches: 2,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 750,
  },
  {
    key: "kwame-mensah",
    name: "Kwame Mensah",
    jobTitle: "Operations Manager",
    email: "kwame.mensah@email.com",
    avatarClassName: "bg-tone-purple",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "ava-thompson",
    name: "Ava Thompson",
    jobTitle: "Medical Writer",
    email: "ava.thompson@email.com",
    avatarClassName: "bg-tone-pink",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "samuel-cohen",
    name: "Samuel Cohen",
    jobTitle: "Tax Manager",
    email: "samuel.cohen@email.com",
    avatarClassName: "bg-tone-success",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "lina-petrova",
    name: "Lina Petrova",
    jobTitle: "Data Engineer",
    email: "lina.petrova@email.com",
    avatarClassName: "bg-tone-warning",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "diego-alvarez",
    name: "Diego Alvarez",
    jobTitle: "Product Manager",
    email: "diego.alvarez@email.com",
    avatarClassName: "bg-tone-orange",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "fatima-zahra",
    name: "Fatima Zahra",
    jobTitle: "Physical Therapist",
    email: "fatima.zahra@email.com",
    avatarClassName: "bg-tone-info",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 300,
  },
  {
    key: "benjamin-wright",
    name: "Benjamin Wright",
    jobTitle: "Actuary",
    email: "benjamin.wright@email.com",
    avatarClassName: "bg-tone-indigo",
    matches: 1,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 450,
  },
  {
    key: "nadia-hussain",
    name: "Nadia Hussain",
    jobTitle: "Compliance Analyst",
    email: "nadia.hussain@email.com",
    avatarClassName: "bg-tone-purple",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "tyler-nguyen",
    name: "Tyler Nguyen",
    jobTitle: "Business Analyst",
    email: "tyler.nguyen@email.com",
    avatarClassName: "bg-tone-pink",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "elena-popescu",
    name: "Elena Popescu",
    jobTitle: "Biostatistician",
    email: "elena.popescu@email.com",
    avatarClassName: "bg-tone-success",
    matches: 1,
    newMatch: true,
    lastActivity: "New match surfaced",
    referrals: 0,
    earned: 0,
    potential: 450,
  },
  {
    key: "jordan-reyes",
    name: "Jordan Reyes",
    jobTitle: "Claims Adjuster",
    email: "jordan.reyes@email.com",
    avatarClassName: "bg-tone-warning",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "zoe-campbell",
    name: "Zoe Campbell",
    jobTitle: "Content Strategist",
    email: "zoe.campbell@email.com",
    avatarClassName: "bg-tone-orange",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "arjun-mehta",
    name: "Arjun Mehta",
    jobTitle: "Quantitative Analyst",
    email: "arjun.mehta@email.com",
    avatarClassName: "bg-tone-info",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "olga-ivanova",
    name: "Olga Ivanova",
    jobTitle: "Clinical Pharmacist",
    email: "olga.ivanova@email.com",
    avatarClassName: "bg-tone-indigo",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "malik-johnson",
    name: "Malik Johnson",
    jobTitle: "Supply Chain Analyst",
    email: "malik.johnson@email.com",
    avatarClassName: "bg-tone-purple",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "rachel-green",
    name: "Rachel Green",
    jobTitle: "Human Resources Manager",
    email: "rachel.green@email.com",
    avatarClassName: "bg-tone-pink",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "tomas-silva",
    name: "Tomás Silva",
    jobTitle: "Financial Auditor",
    email: "tomas.silva@email.com",
    avatarClassName: "bg-tone-success",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "yuki-sato",
    name: "Yuki Sato",
    jobTitle: "AI Research Scientist",
    email: "yuki.sato@email.com",
    avatarClassName: "bg-tone-warning",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "charlotte-evans",
    name: "Charlotte Evans",
    jobTitle: "Corporate Attorney",
    email: "charlotte.evans@email.com",
    avatarClassName: "bg-tone-orange",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
  {
    key: "henry-adeyemi",
    name: "Henry Adeyemi",
    jobTitle: "Revenue Cycle Manager",
    email: "henry.adeyemi@email.com",
    avatarClassName: "bg-tone-info",
    matches: 0,
    referrals: 0,
    earned: 0,
    potential: 0,
  },
];

export { CONNECTION_ACTIVITIES, DEMO_CONNECTIONS, type ConnectionActivity, type DemoConnection };
